import edu.wpi.cs4341.finalProject.Main;
import org.junit.Test;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'jonathanleitschuh' at '10/1/15 9:26 PM' with Gradle 2.6
 *
 * @author jonathanleitschuh, @date 10/1/15 9:26 PM
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Main classUnderTest = new Main();
        //assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
