/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'jonathanleitschuh' at '10/1/15 9:26 PM' with Gradle 2.6
 *
 * @author jonathanleitschuh, @date 10/1/15 9:26 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
